import Head from 'next/head'
import NavBar from './components/Navbar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Dumebi Okolo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10'>
       <NavBar />

      </main>
    </div>
  )
}
